import Head from 'next/head';
import { Flex, Button, Stack } from "@chakra-ui/react";
import { Input } from '../components/Form/Input';

export default function SignIn() {
  return (
    <div>
      <Head>
        <title>Dashgo</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Flex 
        w="100vw" 
        h="100vh" 
        align="center" 
        justify="center"
      >
        <Flex 
          as="form"
          w="100%"
          maxW={ 360 }
          bg="gray.800"
          p="8"
          borderRadius="8"
          flexDirection="column"
        >
          <Stack spacing="4">
            <Input 
              label="E-mail"
              name="email"
              type="email"
            />
            <Input 
              label="Senha"
              name="password"
              type="password"
            />
          </Stack>
          <Button 
            type="submit" 
            mt="6"
            colorScheme="pink"
            size="lg"
          >Entrar</Button>
        </Flex>  
      </Flex>
    </div>
  )
}
